import type { ReviewableChunk } from '../types/diff.types.js';

/**
 * PR metadata passed into the prompt builder.
 */
export interface PRContext {
    title: string;
    description: string | null;
    author: string;
    baseBranch: string;
    headBranch: string;
    language: string | null;
}

/**
 * Repo-specific review configuration.
 */
export interface RepoReviewConfig {
    customInstructions?: string;
    focusAreas?: string[];
    ignorePatterns?: string[];
    severityThreshold?: 'critical' | 'high' | 'medium' | 'low';
    maxIssuesPerFile?: number;
}

// ─── System Prompt ──────────────────────────────────────────────────────

/**
 * The system prompt is fixed across ALL reviews.
 * It defines who the Assistant is, what it prioritizes, and what format to use.
 */
export function getSystemPrompt(): string {
    return `You are a principal-level software engineer conducting a rigorous code review on a GitHub Pull Request. You have 15+ years of experience shipping production systems and have deep expertise in security, distributed systems, and software design.

## YOUR REVIEW PHILOSOPHY

You think like a tech lead reviewing code before it ships to production on Friday afternoon. You care about:

1. **BUGS** — Logic errors, off-by-one mistakes, null/undefined access, race conditions, unhandled promise rejections, incorrect error handling, wrong comparison operators, infinite loops, memory leaks
2. **SECURITY** — SQL injection, XSS, SSRF, path traversal, missing auth checks, secrets in code, insecure crypto, unsafe deserialization, IDOR, open redirects, timing attacks
3. **PERFORMANCE** — N+1 queries, unbounded loops over user data, missing indexes, unnecessary re-renders, synchronous I/O in async paths, O(n²) where O(n) is possible, memory allocation in hot paths
4. **LOGIC ERRORS** — Wrong business logic, incorrect state transitions, missing edge cases, wrong variable in conditional, swapped arguments, incorrect type coercion

You DO NOT care about:
- Style nitpicks (spacing, trailing commas, quote style) — formatters handle this
- Trivial variable renaming unless it causes confusion
- Personal preference ("I would have done it differently")
- Obvious code generated by tooling
- Test file naming conventions

## CRITICAL RULES

1. **Only comment on lines that appear in the diff** — the \`lineNumber\` field MUST reference a line from the added (+) side of the diff.
2. **Every issue must have a concrete fix** — don't just say "this is wrong." Show exactly how to fix it in the \`suggestion\` field.
3. **No false positives** — if you're less than 80% confident something is actually a bug, do NOT report it. Being wrong wastes developer time and erodes trust.
4. **Quality over quantity** — 3 real bugs beat 20 nitpicks. Only report issues that genuinely improve the code.
5. **Understand intent** — read the PR title and description to understand what the author is trying to do. Don't fight the design, review the implementation.
6. **Be constructive, not adversarial** — you're helping a teammate, not gatekeeping.

## COMMON PATTERNS TO CATCH

### JavaScript/TypeScript specific:
- \`==\` instead of \`===\` (type coercion bugs)
- Missing \`await\` on async functions (silent failures)
- \`.catch()\` swallowing errors without logging
- Array.prototype.find() result used without null check
- parseInt() without radix parameter
- Using \`delete\` on arrays (leaves holes)
- JSON.parse() without try/catch
- RegExp ReDoS vulnerabilities
- Prototype pollution via Object.assign with user input
- Missing Content-Type / CORS validation

### Common across all languages:
- TOCTOU (time-of-check-time-of-use) race conditions
- SQL injection via string concatenation
- Logging sensitive data (passwords, tokens, PII)
- Hardcoded secrets / API keys
- Missing input validation on user-facing endpoints
- Path traversal via \`../\` in user input
- Unescaped HTML output (XSS)
- Missing error handling around external service calls

## OUTPUT FORMAT

You MUST respond with ONLY valid JSON (no markdown fences, no explanation text). The JSON must match this exact schema:

\`\`\`
{
  "summary": "string — 2-4 sentence overall assessment. What is this PR doing? Is the implementation sound?",
  "overallVerdict": "approve" | "request_changes" | "comment",
  "issues": [
    {
      "severity": "critical" | "high" | "medium" | "low",
      "type": "bug" | "security" | "performance" | "logic" | "style",
      "filename": "string — exact path from the diff",
      "lineNumber": number — line number in the NEW file (+side of diff),
      "title": "string — concise 5-10 word title for the issue",
      "description": "string — clear explanation of WHY this is a problem, what could go wrong",
      "suggestion": "string — exact code or steps to fix the issue",
      "codeSnippet": "string (optional) — corrected code that can replace the problematic lines"
    }
  ],
  "positives": ["string — things done well worth acknowledging (good error handling, clean abstractions, thorough tests)"],
  "questions": ["string — questions for the author about ambiguous design decisions, not complaints"]
}
\`\`\`

### Verdict decision logic:
- **approve**: No critical or high issues. Code is safe for production.
- **request_changes**: At least one critical or high severity issue. Must be fixed before merge.
- **comment**: Only medium/low issues. Safe to merge but has room for improvement.

### If the code is clean:
Return an empty \`issues\` array, populate \`positives\` with specific things done well, and set verdict to \`approve\`.`;
}

// ─── User Prompt Builder ────────────────────────────────────────────────

/**
 * Build the complete user prompt for a review chunk.
 *
 * Structure:
 *   1. PR context (what the author is trying to do)
 *   2. Repo-specific rules
 *   3. The actual diff with line numbers
 *   4. Surrounding file context (if available)
 */
export function buildReviewPrompt(
    chunk: ReviewableChunk,
    prContext: PRContext,
    repoConfig: RepoReviewConfig,
    fileContexts?: Map<string, string>,
): string {
    const sections: string[] = [];

    // ── 1. PR Context ─────────────────────────────────────────────────

    sections.push('# Pull Request Context\n');
    sections.push(`**Title:** ${prContext.title}`);
    sections.push(`**Author:** ${prContext.author}`);
    sections.push(`**Branch:** \`${prContext.headBranch}\` → \`${prContext.baseBranch}\``);

    if (prContext.language) {
        sections.push(`**Primary Language:** ${prContext.language}`);
    }

    if (prContext.description) {
        const desc = prContext.description.length > 2000
            ? prContext.description.slice(0, 2000) + '\n\n_[description truncated]_'
            : prContext.description;
        sections.push(`\n**Description:**\n${desc}`);
    }

    sections.push(`\n**Files in this review chunk:** ${chunk.files.length}`);
    sections.push(`**Chunk priority:** ${chunk.priority}`);

    // ── 2. Repo-specific rules ────────────────────────────────────────

    if (repoConfig.customInstructions || repoConfig.focusAreas?.length) {
        sections.push('\n---\n# Repository-Specific Review Rules\n');

        if (repoConfig.customInstructions) {
            sections.push(repoConfig.customInstructions);
        }

        if (repoConfig.focusAreas && repoConfig.focusAreas.length > 0) {
            sections.push('\n**Focus Areas (pay extra attention to):**');
            for (const area of repoConfig.focusAreas) {
                sections.push(`- ${area}`);
            }
        }

        if (repoConfig.severityThreshold) {
            sections.push(`\n**Severity Threshold:** Only report issues at \`${repoConfig.severityThreshold}\` or above.`);
        }

        if (repoConfig.maxIssuesPerFile) {
            sections.push(`**Max Issues Per File:** ${repoConfig.maxIssuesPerFile} (focus on the most important)`);
        }
    }

    // ── 3. Diff content ───────────────────────────────────────────────

    sections.push('\n---\n# Changed Files\n');
    sections.push('Review the following diff carefully. Each file shows the unified diff with line numbers.\n');

    for (const file of chunk.files) {
        sections.push(`## File: \`${file.filename}\``);
        sections.push(`- **Status:** ${file.status}${file.oldFilename ? ` (renamed from \`${file.oldFilename}\`)` : ''}`);
        sections.push(`- **Language:** ${file.language}`);
        sections.push(`- **Changes:** +${file.additions} / -${file.deletions}`);

        if (file.isBinary) {
            sections.push('\n_Binary file — cannot review content._\n');
            continue;
        }

        if (file.hunks.length === 0) {
            sections.push('\n_No content changes (possibly permission or mode change)._\n');
            continue;
        }

        // ── Surrounding context (if available) ────────────────────────

        const context = fileContexts?.get(file.filename);
        if (context) {
            sections.push('\n<surrounding_context>');
            sections.push('This is the existing code around the changed areas for reference:');
            sections.push('```');
            // Truncate context to 3000 chars to avoid bloating prompt
            sections.push(context.length > 3000 ? context.slice(0, 3000) + '\n// ... truncated' : context);
            sections.push('```');
            sections.push('</surrounding_context>');
        }

        // ── Diff hunks with line numbers ─────────────────────────────

        sections.push('\n<diff>');

        for (const hunk of file.hunks) {
            sections.push(`\n${hunk.header}`);
            if (hunk.context) {
                sections.push(`// Context: ${hunk.context}`);
            }

            for (const line of hunk.lines) {
                const prefix = line.type === 'add' ? '+' : line.type === 'remove' ? '-' : ' ';
                const lineNum = line.type === 'remove'
                    ? `L${line.oldLineNumber ?? '?'}`
                    : `L${line.newLineNumber ?? '?'}`;

                sections.push(`${lineNum.padEnd(6)} ${prefix} ${line.content}`);
            }
        }

        sections.push('</diff>\n');
    }

    // ── 4. Final instruction ──────────────────────────────────────────

    sections.push('---');
    sections.push('Now analyze the diff above. Remember:');
    sections.push('- ONLY reference lines from the diff (+ side) in your lineNumber fields');
    sections.push('- Every issue needs a concrete suggestion showing how to fix it');
    sections.push('- If the code is clean, say so — an empty issues array is fine');
    sections.push('- Respond with raw JSON only, no markdown code fences');

    return sections.join('\n');
}

// ─── JSON Repair Prompt ─────────────────────────────────────────────────

/**
 * Follow-up prompt when the LLM returns malformed JSON.
 */
export function buildRepairPrompt(malformedResponse: string, error: string): string {
    return `Your previous response was not valid JSON. Here's the error:

ERROR: ${error}

YOUR RESPONSE (first 3000 chars):
${malformedResponse.slice(0, 3000)}

Please return ONLY the corrected JSON matching the schema from the system prompt. Rules:
1. No markdown code fences (\`\`\`json ... \`\`\`)
2. No explanation text before or after
3. All string values must be properly escaped
4. All arrays must be valid (no trailing commas)
5. Return raw JSON only`;
}
